services:

  node:
    container_name: node
    image: node:18.13.0-alpine
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

    ports:
      - '8081:8081'
    command: sh -c "npm i && npm run start-app"

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 5

volumes:
  mongo_data: